name: Setup OpenModelica Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kzscisoft/run-openmodelica-model@v1
        with:
          model_name: SineCurrentModel
          libraries: Modelica BioChem
          file_path: test/SineCurrentModel.mo