name: Setup OpenModelica Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kzscisoft/setup-openmodelica@v1
        with:
          version: 1.13.0
      - run: omc --version